/**
 * Audit Log Actions and Result Constants.
 *
 * Defines standard action names and outcome states for structured audit logging
 * across authentication, user management, master data, and budget allocations.
 */

export const AUDIT_ACTIONS = {
  // Authentication & Authorization
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',

  // User Management
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',

  // Master Data - Fiscal Year
  FISCAL_YEAR_CREATE: 'FISCAL_YEAR_CREATE',
  FISCAL_YEAR_UPDATE: 'FISCAL_YEAR_UPDATE',
  FISCAL_YEAR_DELETE: 'FISCAL_YEAR_DELETE',
  FISCAL_YEAR_ACTIVATE: 'FISCAL_YEAR_ACTIVATE',

  // Master Data - Fund Source
  FUND_SOURCE_CREATE: 'FUND_SOURCE_CREATE',
  FUND_SOURCE_UPDATE: 'FUND_SOURCE_UPDATE',
  FUND_SOURCE_DELETE: 'FUND_SOURCE_DELETE',

  // Master Data - Department
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',

  // Master Data - Budget Category
  BUDGET_CATEGORY_CREATE: 'BUDGET_CATEGORY_CREATE',
  BUDGET_CATEGORY_UPDATE: 'BUDGET_CATEGORY_UPDATE',
  BUDGET_CATEGORY_DELETE: 'BUDGET_CATEGORY_DELETE',

  // Master Data - Budget Program
  BUDGET_PROGRAM_CREATE: 'BUDGET_PROGRAM_CREATE',
  BUDGET_PROGRAM_UPDATE: 'BUDGET_PROGRAM_UPDATE',
  BUDGET_PROGRAM_DELETE: 'BUDGET_PROGRAM_DELETE',

  // Budget Allocations
  ALLOCATION_CREATE: 'ALLOCATION_CREATE',
  ALLOCATION_UPDATE: 'ALLOCATION_UPDATE',
  ALLOCATION_DELETE: 'ALLOCATION_DELETE',
  ALLOCATION_STATUS_CHANGE: 'ALLOCATION_STATUS_CHANGE',
  ALLOCATION_SUBMIT: 'ALLOCATION_SUBMIT',
  ALLOCATION_APPROVE: 'ALLOCATION_APPROVE',
  ALLOCATION_REJECT: 'ALLOCATION_REJECT',
  ALLOCATION_RETURN: 'ALLOCATION_RETURN',

  // Blockchain Ledger
  BLOCKCHAIN_RECORD: 'BLOCKCHAIN_RECORD',
  BLOCKCHAIN_VERIFY: 'BLOCKCHAIN_VERIFY',
  BLOCKCHAIN_RETRY: 'BLOCKCHAIN_RETRY',

  // Audit Trail Anchoring (Phase 4.6 M3)
  AUDIT_ANCHOR_RETRY: 'AUDIT_ANCHOR_RETRY',

  // Document Management
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  DOCUMENT_REPLACE: 'DOCUMENT_REPLACE',
  DOCUMENT_ARCHIVE: 'DOCUMENT_ARCHIVE',
  DOCUMENT_VERIFY: 'DOCUMENT_VERIFY',
  DOCUMENT_ANCHOR_RETRY: 'DOCUMENT_ANCHOR_RETRY',
};

export const AUDIT_RESULTS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};
